use_frameworks!

platform :ios, '9.0'

target 'MockServiceSwift_Example' do
  pod 'MockServiceSwift', :path => '../'
  pod 'Moya'

  target 'MockServiceSwift_Tests' do
    inherit! :search_paths

    
  end
end
